use wasm_bindgen::prelude::*;
use glam::Vec3;

/// Core flight physics engine for the wireframe shooter.
/// Holds all numerical state — never touches DOM or JS objects.
#[wasm_bindgen]
pub struct GameEngine {
    // Position & orientation
    pos: Vec3,
    pitch: f32,
    yaw: f32,
    roll: f32,
    velocity: Vec3,

    // Throttle
    min_throttle: f32,
    max_throttle: f32,
    throttle: f32,

    // Physics
    gravity: f32,

    // Stamina / boost
    max_stamina: f32,
    stamina: f32,
    stamina_drain_rate: f32,
    stamina_regen_rate: f32,
    is_boosting: bool,
    was_boosting: bool,
    stamina_depleted: bool,

    // FOV
    base_fov: f32,
    boost_fov: f32,
    target_fov: f32,

    // HP
    max_hp: f32,
    hp: f32,

    // Stall
    stall_pitch_threshold: f32,
    stall_time_required: f32,
    stall_timer: f32,
    is_stalled: bool,
    stall_recovery_progress: f32,
    prev_control_pressed: bool,
    infinite_engines_active: bool,
    shield_active: bool,

    // Death state
    is_dying: bool,
    die_from_high: bool,

    // Terrain
    terrain_warning: bool,
    terrain_crashed: bool,
    altitude: f32,
    is_above_max_alt: bool,

    // Camera shake
    shake_timer: f32,
    shake_duration: f32,
    shake_intensity: f32,
    shake_intensity_scale: f32,

    // Whether a shake was triggered this frame (for boost detection)
    shake_triggered_this_frame: bool,

    // Shared memory buffers — written every tick, read by JS
    transform_buf: [f32; 7],  // [pos_x, pos_y, pos_z, pitch, yaw, roll, target_fov]
    state_buf: [f32; 18],     // game state floats
    velocity_buf: [f32; 3],   // [vx, vy, vz]
}

#[wasm_bindgen]
impl GameEngine {
    /// Create a new GameEngine with default flight parameters.
    /// `init_x`, `init_z` are the random spawn coordinates generated by JS.
    #[wasm_bindgen(constructor)]
    pub fn new(init_x: f32, init_z: f32) -> GameEngine {
        GameEngine {
            pos: Vec3::new(init_x, 500.0, init_z),
            pitch: -0.05,
            yaw: 0.0,
            roll: 0.0,
            velocity: Vec3::new(0.0, 0.0, -140.0),

            min_throttle: 60.0,
            max_throttle: 260.0,
            throttle: 140.0,

            gravity: -12.0,

            max_stamina: 100.0,
            stamina: 100.0,
            stamina_drain_rate: 30.0,
            stamina_regen_rate: 15.0,
            is_boosting: false,
            was_boosting: false,
            stamina_depleted: false,

            base_fov: 90.0,
            boost_fov: 120.0,
            target_fov: 90.0,

            max_hp: 100.0,
            hp: 100.0,

            stall_pitch_threshold: 0.8,
            stall_time_required: 1.5,
            stall_timer: 0.0,
            is_stalled: false,
            stall_recovery_progress: 0.0,
            prev_control_pressed: false,
            infinite_engines_active: false,
            shield_active: false,

            is_dying: false,
            die_from_high: false,

            terrain_warning: false,
            terrain_crashed: false,
            altitude: 0.0,
            is_above_max_alt: false,

            shake_timer: 0.0,
            shake_duration: 0.22,
            shake_intensity: 0.0,
            shake_intensity_scale: 0.8, // default 80%

            shake_triggered_this_frame: false,

            transform_buf: [0.0; 7],
            state_buf: [0.0; 18],
            velocity_buf: [0.0; 3],
        }
    }

    /// Placeholder tick — will be filled in commits 3-5.
    pub fn tick(&mut self, _dt: f32) {
        self.write_buffers();
    }

    /// Returns a pointer to the transform buffer (7 f32s).
    pub fn get_transform_ptr(&self) -> *const f32 {
        self.transform_buf.as_ptr()
    }

    /// Returns a pointer to the state buffer (18 f32s).
    pub fn get_state_ptr(&self) -> *const f32 {
        self.state_buf.as_ptr()
    }

    /// Returns a pointer to the velocity buffer (3 f32s).
    pub fn get_velocity_ptr(&self) -> *const f32 {
        self.velocity_buf.as_ptr()
    }
}

// Private helpers (not exposed to JS)
impl GameEngine {
    /// Write current state into the shared memory buffers.
    fn write_buffers(&mut self) {
        // Transform buffer
        self.transform_buf[0] = self.pos.x;
        self.transform_buf[1] = self.pos.y;
        self.transform_buf[2] = self.pos.z;
        self.transform_buf[3] = self.pitch;
        self.transform_buf[4] = self.yaw;
        self.transform_buf[5] = self.roll;
        self.transform_buf[6] = self.target_fov;

        // State buffer
        self.state_buf[0] = self.hp;
        self.state_buf[1] = self.max_hp;
        self.state_buf[2] = self.stamina;
        self.state_buf[3] = self.max_stamina;
        self.state_buf[4] = if self.is_stalled { 1.0 } else { 0.0 };
        self.state_buf[5] = self.altitude;
        self.state_buf[6] = self.velocity.length();
        self.state_buf[7] = if self.is_boosting { 1.0 } else { 0.0 };
        self.state_buf[8] = if self.stamina_depleted { 1.0 } else { 0.0 };
        self.state_buf[9] = if self.terrain_warning { 1.0 } else { 0.0 };
        self.state_buf[10] = if self.terrain_crashed { 1.0 } else { 0.0 };
        self.state_buf[11] = if self.shield_active { 1.0 } else { 0.0 };
        self.state_buf[12] = self.stall_recovery_progress;
        self.state_buf[13] = if self.is_above_max_alt { 1.0 } else { 0.0 };
        // Shake: amplitude and progress for JS to apply quaternion perturbation
        let shake_progress = if self.shake_duration > 0.0 {
            self.shake_timer / self.shake_duration
        } else {
            0.0
        };
        self.state_buf[14] = self.shake_intensity * shake_progress * 0.04; // amplitude
        self.state_buf[15] = shake_progress;
        self.state_buf[16] = if self.is_dying { 1.0 } else { 0.0 };
        self.state_buf[17] = self.throttle;

        // Velocity buffer
        self.velocity_buf[0] = self.velocity.x;
        self.velocity_buf[1] = self.velocity.y;
        self.velocity_buf[2] = self.velocity.z;
    }
}
