use wasm_bindgen::prelude::*;
use glam::Vec3;

mod engine;
mod entities;
mod systems;

// Re-export utility functions
pub mod utils {
    pub fn lerp(a: f32, b: f32, t: f32) -> f32 {
        a + (b - a) * t
    }
}

use engine::GameEngine as InnerGameEngine;

// ─── InputState ────────────────────────────────────────────────────────────────

#[wasm_bindgen]
#[derive(Clone, Copy)]
pub struct InputState {
    pub is_mobile: bool,
    pub is_boosting: bool,
    pub is_forward: bool,
    pub is_backward: bool,
    pub is_left: bool,
    pub is_right: bool,
    pub mouse_movement_x: f32,
    pub mouse_movement_y: f32,
    pub gyro_pitch_amt: f32,
    pub gyro_roll_amt: f32,
    pub is_stalled_recovery_key: bool,
}

#[wasm_bindgen]
impl InputState {
    #[wasm_bindgen(constructor)]
    pub fn new() -> InputState {
        InputState {
            is_mobile: false,
            is_boosting: false,
            is_forward: false,
            is_backward: false,
            is_left: false,
            is_right: false,
            mouse_movement_x: 0.0,
            mouse_movement_y: 0.0,
            gyro_pitch_amt: 0.0,
            gyro_roll_amt: 0.0,
            is_stalled_recovery_key: false,
        }
    }
}

// ─── GameEngine (wasm_bindgen wrapper) ─────────────────────────────────────────

/// Thin wasm_bindgen wrapper around the inner GameEngine.
/// All #[wasm_bindgen] annotations live here — the inner engine is pure Rust.
#[wasm_bindgen]
pub struct GameEngine {
    inner: InnerGameEngine,
}

#[wasm_bindgen]
impl GameEngine {
    /// Create a new GameEngine with default flight parameters.
    /// `init_x`, `init_z` are the random spawn coordinates generated by JS.
    #[wasm_bindgen(constructor)]
    pub fn new(init_x: f32, init_z: f32) -> GameEngine {
        GameEngine {
            inner: InnerGameEngine::new(init_x, init_z),
        }
    }

    pub fn tick(&mut self, dt: f32, input: &InputState, terrain_height: f32, is_intro: bool) -> bool {
        self.inner.tick(dt, input, terrain_height, is_intro)
    }

    /// Returns a pointer to the transform buffer (7 f32s).
    pub fn get_transform_ptr(&self) -> *const f32 {
        self.inner.transform_buf.as_ptr()
    }

    /// Returns a pointer to the state buffer (18 f32s).
    pub fn get_state_ptr(&self) -> *const f32 {
        self.inner.state_buf.as_ptr()
    }

    /// Returns a pointer to the velocity buffer (3 f32s).
    pub fn get_velocity_ptr(&self) -> *const f32 {
        self.inner.velocity_buf.as_ptr()
    }

    pub fn trigger_shake(&mut self, intensity: f32) {
        self.inner.player.trigger_shake(intensity);
    }

    pub fn die(&mut self) {
        self.inner.player.die();
    }

    pub fn reset(&mut self) {
        self.inner.player.reset();
    }

    pub fn set_pos(&mut self, x: f32, y: f32, z: f32) {
        self.inner.player.pos = Vec3::new(x, y, z);
    }

    pub fn set_hp(&mut self, value: f32) {
        self.inner.player.hp = value.clamp(0.0, self.inner.player.max_hp);
    }

    pub fn set_shield_active(&mut self, active: bool) {
        self.inner.player.shield_active = active;
    }

    pub fn set_infinite_engines_active(&mut self, active: bool) {
        self.inner.player.infinite_engines_active = active;
    }

    pub fn set_stall_timer(&mut self, value: f32) {
        self.inner.player.stall_timer = value;
    }

    pub fn set_is_stalled(&mut self, stalled: bool) {
        self.inner.player.is_stalled = stalled;
    }

    pub fn set_yaw(&mut self, value: f32) {
        self.inner.player.yaw = value;
    }

    pub fn set_pitch(&mut self, value: f32) {
        self.inner.player.pitch = value;
    }

    pub fn set_roll(&mut self, value: f32) {
        self.inner.player.roll = value;
    }
}

// ─── Collision Utilities (stateless, exported to JS) ───────────────────────────

/// Line segment vs sphere intersection test.
/// Used by WeaponSystem._checkCollisions() for laser-vs-enemy.
#[wasm_bindgen]
pub fn line_sphere_intersect(
    lx0: f32, ly0: f32, lz0: f32,
    lx1: f32, ly1: f32, lz1: f32,
    cx: f32, cy: f32, cz: f32,
    radius: f32,
) -> bool {
    systems::collisions::line_sphere_intersect(
        Vec3::new(lx0, ly0, lz0),
        Vec3::new(lx1, ly1, lz1),
        Vec3::new(cx, cy, cz),
        radius,
    )
}

/// Point vs sphere (squared distance) test.
/// Used by EnemyManager._updateEnemyProjectiles() for projectile-vs-player.
#[wasm_bindgen]
pub fn point_in_sphere_sq(
    px: f32, py: f32, pz: f32,
    cx: f32, cy: f32, cz: f32,
    radius_sq: f32,
) -> bool {
    systems::collisions::point_in_sphere_sq(
        Vec3::new(px, py, pz),
        Vec3::new(cx, cy, cz),
        radius_sq,
    )
}
