use wasm_bindgen::prelude::*;
use glam::Vec3;

mod engine;
mod entities;
mod systems;

// Re-export utility functions
pub mod utils {
    pub fn lerp(a: f32, b: f32, t: f32) -> f32 {
        a + (b - a) * t
    }
}

use engine::GameEngine as InnerGameEngine;

// ─── InputState ────────────────────────────────────────────────────────────────

#[wasm_bindgen]
#[derive(Clone, Copy)]
pub struct InputState {
    pub is_mobile: bool,
    pub is_boosting: bool,
    pub is_forward: bool,
    pub is_backward: bool,
    pub is_left: bool,
    pub is_right: bool,
    pub mouse_movement_x: f32,
    pub mouse_movement_y: f32,
    pub gyro_pitch_amt: f32,
    pub gyro_roll_amt: f32,
    pub is_stalled_recovery_key: bool,
}

#[wasm_bindgen]
impl InputState {
    #[wasm_bindgen(constructor)]
    pub fn new() -> InputState {
        InputState {
            is_mobile: false,
            is_boosting: false,
            is_forward: false,
            is_backward: false,
            is_left: false,
            is_right: false,
            mouse_movement_x: 0.0,
            mouse_movement_y: 0.0,
            gyro_pitch_amt: 0.0,
            gyro_roll_amt: 0.0,
            is_stalled_recovery_key: false,
        }
    }
}

// ─── GameEngine (wasm_bindgen wrapper) ─────────────────────────────────────────

/// Thin wasm_bindgen wrapper around the inner GameEngine.
/// All #[wasm_bindgen] annotations live here — the inner engine is pure Rust.
#[wasm_bindgen]
pub struct GameEngine {
    inner: InnerGameEngine,
}

#[wasm_bindgen]
impl GameEngine {
    /// Create a new GameEngine with default flight parameters.
    /// `init_x`, `init_z` are the random spawn coordinates generated by JS.
    #[wasm_bindgen(constructor)]
    pub fn new(init_x: f32, init_z: f32) -> GameEngine {
        GameEngine {
            inner: InnerGameEngine::new(init_x, init_z),
        }
    }

    pub fn tick(&mut self, dt: f32, input: &InputState, terrain_height: f32, is_intro: bool) -> bool {
        self.inner.tick(dt, input, terrain_height, is_intro)
    }

    /// Returns a pointer to the transform buffer (7 f32s).
    pub fn get_transform_ptr(&self) -> *const f32 {
        self.inner.transform_buf.as_ptr()
    }

    /// Returns a pointer to the state buffer (18 f32s).
    pub fn get_state_ptr(&self) -> *const f32 {
        self.inner.state_buf.as_ptr()
    }

    /// Returns a pointer to the velocity buffer (3 f32s).
    pub fn get_velocity_ptr(&self) -> *const f32 {
        self.inner.velocity_buf.as_ptr()
    }

    pub fn trigger_shake(&mut self, intensity: f32) {
        self.inner.player.trigger_shake(intensity);
    }

    pub fn die(&mut self) {
        self.inner.player.die();
    }

    pub fn reset(&mut self) {
        self.inner.player.reset();
    }

    pub fn set_pos(&mut self, x: f32, y: f32, z: f32) {
        self.inner.player.pos = Vec3::new(x, y, z);
    }

    pub fn set_hp(&mut self, value: f32) {
        self.inner.player.hp = value.clamp(0.0, self.inner.player.max_hp);
    }

    pub fn set_shield_active(&mut self, active: bool) {
        self.inner.player.shield_active = active;
    }

    pub fn set_infinite_engines_active(&mut self, active: bool) {
        self.inner.player.infinite_engines_active = active;
    }

    pub fn set_stall_timer(&mut self, value: f32) {
        self.inner.player.stall_timer = value;
    }

    pub fn set_is_stalled(&mut self, stalled: bool) {
        self.inner.player.is_stalled = stalled;
    }

    pub fn set_yaw(&mut self, value: f32) {
        self.inner.player.yaw = value;
    }

    pub fn set_pitch(&mut self, value: f32) {
        self.inner.player.pitch = value;
    }

    pub fn set_roll(&mut self, value: f32) {
        self.inner.player.roll = value;
    }
}

// ─── ParticleEngine (wasm_bindgen wrapper) ─────────────────────────────────────

use systems::particles::ParticleEngine as InnerParticleEngine;

/// Particle physics engine exposed to JS.
/// Manages the lifecycle, physics, and output buffers for all particles.
#[wasm_bindgen]
pub struct ParticleEngine {
    inner: InnerParticleEngine,
}

#[wasm_bindgen]
impl ParticleEngine {
    /// Create a new particle engine.
    /// `max_particles`: 4000 desktop, 1500 mobile.
    #[wasm_bindgen(constructor)]
    pub fn new(max_particles: u32, is_mobile: bool) -> ParticleEngine {
        ParticleEngine {
            inner: InnerParticleEngine::new(max_particles, is_mobile),
        }
    }

    /// Advance all particles by `dt`. Returns the number of active particles.
    pub fn update(&mut self, dt: f32) -> u32 {
        self.inner.update(dt)
    }

    /// Spawn an airburst explosion at (x,y,z).
    pub fn spawn_airburst(&mut self, x: f32, y: f32, z: f32, burst_count: u32) {
        self.inner.spawn_airburst(x, y, z, burst_count);
    }

    /// Spawn a ground explosion at (x,y,z).
    pub fn spawn_ground_explosion(&mut self, x: f32, y: f32, z: f32, ground_count: u32) {
        self.inner.spawn_ground_explosion(x, y, z, ground_count);
    }

    /// Spawn a laser impact splash at (x,y,z).
    pub fn spawn_laser_impact(&mut self, x: f32, y: f32, z: f32, impact_count: u32) {
        self.inner.spawn_laser_impact(x, y, z, impact_count);
    }

    /// Find first free particle slot. Returns index or -1 if full.
    pub fn get_free(&mut self) -> i32 {
        self.inner.get_free()
    }

    /// Activate a specific particle by index with full parameters.
    pub fn activate(
        &mut self,
        index: u32,
        x: f32, y: f32, z: f32,
        vx: f32, vy: f32, vz: f32,
        life: f32,
        r: f32, g: f32, b: f32,
    ) {
        self.inner.activate(index, x, y, z, vx, vy, vz, life, r, g, b);
    }

    /// Returns a pointer to the 4x4 matrix buffer (active_count × 16 f32s).
    pub fn get_matrix_ptr(&self) -> *const f32 {
        self.inner.get_matrix_ptr()
    }

    /// Returns a pointer to the RGB color buffer (active_count × 3 f32s).
    pub fn get_color_ptr(&self) -> *const f32 {
        self.inner.get_color_ptr()
    }

    /// Returns the number of active particles after the last update().
    pub fn get_active_count(&self) -> u32 {
        self.inner.get_active_count()
    }

    /// Deactivate all particles.
    pub fn reset(&mut self) {
        self.inner.reset();
    }
}

// ─── Collision Utilities (stateless, exported to JS) ───────────────────────────

#[wasm_bindgen]
pub fn check_bulk_laser_hits(
    enemy_ptr: *const f32,
    enemy_count: u32,
    laser_ptr: *const f32,
    laser_count: u32,
) {
    systems::collisions::check_bulk_laser_hits(enemy_ptr, enemy_count, laser_ptr, laser_count);
}

#[wasm_bindgen]
pub fn check_bulk_enemy_projectiles(
    proj_ptr: *const f32,
    proj_count: u32,
    px: f32,
    py: f32,
    pz: f32,
    radius_sq: f32,
) {
    systems::collisions::check_bulk_enemy_projectiles(proj_ptr, proj_count, px, py, pz, radius_sq);
}

#[wasm_bindgen]
pub fn get_hit_results_ptr() -> *const i32 {
    systems::collisions::HIT_RESULTS_BUF.with(|buf| buf.borrow().as_ptr())
}

#[wasm_bindgen]
pub fn get_hit_results_len() -> u32 {
    systems::collisions::HIT_RESULTS_BUF.with(|buf| buf.borrow().len() as u32)
}

#[wasm_bindgen]
pub fn engine_memory_alloc(size: usize) -> *mut u8 {
    let mut buf = Vec::with_capacity(size);
    let ptr = buf.as_mut_ptr();
    std::mem::forget(buf);
    ptr
}

#[wasm_bindgen]
pub fn engine_memory_free(ptr: *mut u8, size: usize) {
    unsafe {
        drop(Vec::from_raw_parts(ptr, 0, size));
    }
}

