/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_gameengine_free: (a: number, b: number) => void;
export const __wbg_get_inputstate_gyro_pitch_amt: (a: number) => number;
export const __wbg_get_inputstate_gyro_roll_amt: (a: number) => number;
export const __wbg_get_inputstate_is_backward: (a: number) => number;
export const __wbg_get_inputstate_is_boosting: (a: number) => number;
export const __wbg_get_inputstate_is_forward: (a: number) => number;
export const __wbg_get_inputstate_is_left: (a: number) => number;
export const __wbg_get_inputstate_is_mobile: (a: number) => number;
export const __wbg_get_inputstate_is_right: (a: number) => number;
export const __wbg_get_inputstate_is_stalled_recovery_key: (a: number) => number;
export const __wbg_get_inputstate_mouse_movement_x: (a: number) => number;
export const __wbg_get_inputstate_mouse_movement_y: (a: number) => number;
export const __wbg_inputstate_free: (a: number, b: number) => void;
export const __wbg_set_inputstate_gyro_pitch_amt: (a: number, b: number) => void;
export const __wbg_set_inputstate_gyro_roll_amt: (a: number, b: number) => void;
export const __wbg_set_inputstate_is_backward: (a: number, b: number) => void;
export const __wbg_set_inputstate_is_boosting: (a: number, b: number) => void;
export const __wbg_set_inputstate_is_forward: (a: number, b: number) => void;
export const __wbg_set_inputstate_is_left: (a: number, b: number) => void;
export const __wbg_set_inputstate_is_mobile: (a: number, b: number) => void;
export const __wbg_set_inputstate_is_right: (a: number, b: number) => void;
export const __wbg_set_inputstate_is_stalled_recovery_key: (a: number, b: number) => void;
export const __wbg_set_inputstate_mouse_movement_x: (a: number, b: number) => void;
export const __wbg_set_inputstate_mouse_movement_y: (a: number, b: number) => void;
export const gameengine_die: (a: number) => void;
export const gameengine_get_state_ptr: (a: number) => number;
export const gameengine_get_transform_ptr: (a: number) => number;
export const gameengine_get_velocity_ptr: (a: number) => number;
export const gameengine_new: (a: number, b: number) => number;
export const gameengine_reset: (a: number) => void;
export const gameengine_set_hp: (a: number, b: number) => void;
export const gameengine_set_infinite_engines_active: (a: number, b: number) => void;
export const gameengine_set_is_stalled: (a: number, b: number) => void;
export const gameengine_set_pitch: (a: number, b: number) => void;
export const gameengine_set_pos: (a: number, b: number, c: number, d: number) => void;
export const gameengine_set_roll: (a: number, b: number) => void;
export const gameengine_set_shield_active: (a: number, b: number) => void;
export const gameengine_set_stall_timer: (a: number, b: number) => void;
export const gameengine_set_yaw: (a: number, b: number) => void;
export const gameengine_tick: (a: number, b: number, c: number, d: number, e: number) => number;
export const gameengine_trigger_shake: (a: number, b: number) => void;
export const inputstate_new: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
