/* @ts-self-types="./core_engine.d.ts" */

/**
 * Core flight physics engine for the wireframe shooter.
 * Holds all numerical state — never touches DOM or JS objects.
 */
export class GameEngine {
    __destroy_into_raw() {
        const ptr = this.__wbg_ptr;
        this.__wbg_ptr = 0;
        GameEngineFinalization.unregister(this);
        return ptr;
    }
    free() {
        const ptr = this.__destroy_into_raw();
        wasm.__wbg_gameengine_free(ptr, 0);
    }
    die() {
        wasm.gameengine_die(this.__wbg_ptr);
    }
    /**
     * Returns a pointer to the state buffer (18 f32s).
     * @returns {number}
     */
    get_state_ptr() {
        const ret = wasm.gameengine_get_state_ptr(this.__wbg_ptr);
        return ret >>> 0;
    }
    /**
     * Returns a pointer to the transform buffer (7 f32s).
     * @returns {number}
     */
    get_transform_ptr() {
        const ret = wasm.gameengine_get_transform_ptr(this.__wbg_ptr);
        return ret >>> 0;
    }
    /**
     * Returns a pointer to the velocity buffer (3 f32s).
     * @returns {number}
     */
    get_velocity_ptr() {
        const ret = wasm.gameengine_get_velocity_ptr(this.__wbg_ptr);
        return ret >>> 0;
    }
    /**
     * Create a new GameEngine with default flight parameters.
     * `init_x`, `init_z` are the random spawn coordinates generated by JS.
     * @param {number} init_x
     * @param {number} init_z
     */
    constructor(init_x, init_z) {
        const ret = wasm.gameengine_new(init_x, init_z);
        this.__wbg_ptr = ret;
        GameEngineFinalization.register(this, this.__wbg_ptr, this);
        return this;
    }
    reset() {
        wasm.gameengine_reset(this.__wbg_ptr);
    }
    /**
     * @param {number} value
     */
    set_hp(value) {
        wasm.gameengine_set_hp(this.__wbg_ptr, value);
    }
    /**
     * @param {boolean} active
     */
    set_infinite_engines_active(active) {
        wasm.gameengine_set_infinite_engines_active(this.__wbg_ptr, active);
    }
    /**
     * @param {boolean} stalled
     */
    set_is_stalled(stalled) {
        wasm.gameengine_set_is_stalled(this.__wbg_ptr, stalled);
    }
    /**
     * @param {number} value
     */
    set_pitch(value) {
        wasm.gameengine_set_pitch(this.__wbg_ptr, value);
    }
    /**
     * @param {number} x
     * @param {number} y
     * @param {number} z
     */
    set_pos(x, y, z) {
        wasm.gameengine_set_pos(this.__wbg_ptr, x, y, z);
    }
    /**
     * @param {number} value
     */
    set_roll(value) {
        wasm.gameengine_set_roll(this.__wbg_ptr, value);
    }
    /**
     * @param {boolean} active
     */
    set_shield_active(active) {
        wasm.gameengine_set_shield_active(this.__wbg_ptr, active);
    }
    /**
     * @param {number} value
     */
    set_stall_timer(value) {
        wasm.gameengine_set_stall_timer(this.__wbg_ptr, value);
    }
    /**
     * @param {number} value
     */
    set_yaw(value) {
        wasm.gameengine_set_yaw(this.__wbg_ptr, value);
    }
    /**
     * @param {number} dt
     * @param {InputState} input
     * @param {number} terrain_height
     * @param {boolean} is_intro
     * @returns {boolean}
     */
    tick(dt, input, terrain_height, is_intro) {
        _assertClass(input, InputState);
        const ret = wasm.gameengine_tick(this.__wbg_ptr, dt, input.__wbg_ptr, terrain_height, is_intro);
        return ret !== 0;
    }
    /**
     * @param {number} intensity
     */
    trigger_shake(intensity) {
        wasm.gameengine_trigger_shake(this.__wbg_ptr, intensity);
    }
}
if (Symbol.dispose) GameEngine.prototype[Symbol.dispose] = GameEngine.prototype.free;

export class InputState {
    __destroy_into_raw() {
        const ptr = this.__wbg_ptr;
        this.__wbg_ptr = 0;
        InputStateFinalization.unregister(this);
        return ptr;
    }
    free() {
        const ptr = this.__destroy_into_raw();
        wasm.__wbg_inputstate_free(ptr, 0);
    }
    /**
     * @returns {number}
     */
    get gyro_pitch_amt() {
        const ret = wasm.__wbg_get_inputstate_gyro_pitch_amt(this.__wbg_ptr);
        return ret;
    }
    /**
     * @returns {number}
     */
    get gyro_roll_amt() {
        const ret = wasm.__wbg_get_inputstate_gyro_roll_amt(this.__wbg_ptr);
        return ret;
    }
    /**
     * @returns {boolean}
     */
    get is_backward() {
        const ret = wasm.__wbg_get_inputstate_is_backward(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
     * @returns {boolean}
     */
    get is_boosting() {
        const ret = wasm.__wbg_get_inputstate_is_boosting(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
     * @returns {boolean}
     */
    get is_forward() {
        const ret = wasm.__wbg_get_inputstate_is_forward(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
     * @returns {boolean}
     */
    get is_left() {
        const ret = wasm.__wbg_get_inputstate_is_left(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
     * @returns {boolean}
     */
    get is_mobile() {
        const ret = wasm.__wbg_get_inputstate_is_mobile(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
     * @returns {boolean}
     */
    get is_right() {
        const ret = wasm.__wbg_get_inputstate_is_right(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
     * @returns {boolean}
     */
    get is_stalled_recovery_key() {
        const ret = wasm.__wbg_get_inputstate_is_stalled_recovery_key(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
     * @returns {number}
     */
    get mouse_movement_x() {
        const ret = wasm.__wbg_get_inputstate_mouse_movement_x(this.__wbg_ptr);
        return ret;
    }
    /**
     * @returns {number}
     */
    get mouse_movement_y() {
        const ret = wasm.__wbg_get_inputstate_mouse_movement_y(this.__wbg_ptr);
        return ret;
    }
    constructor() {
        const ret = wasm.inputstate_new();
        this.__wbg_ptr = ret;
        InputStateFinalization.register(this, this.__wbg_ptr, this);
        return this;
    }
    /**
     * @param {number} arg0
     */
    set gyro_pitch_amt(arg0) {
        wasm.__wbg_set_inputstate_gyro_pitch_amt(this.__wbg_ptr, arg0);
    }
    /**
     * @param {number} arg0
     */
    set gyro_roll_amt(arg0) {
        wasm.__wbg_set_inputstate_gyro_roll_amt(this.__wbg_ptr, arg0);
    }
    /**
     * @param {boolean} arg0
     */
    set is_backward(arg0) {
        wasm.__wbg_set_inputstate_is_backward(this.__wbg_ptr, arg0);
    }
    /**
     * @param {boolean} arg0
     */
    set is_boosting(arg0) {
        wasm.__wbg_set_inputstate_is_boosting(this.__wbg_ptr, arg0);
    }
    /**
     * @param {boolean} arg0
     */
    set is_forward(arg0) {
        wasm.__wbg_set_inputstate_is_forward(this.__wbg_ptr, arg0);
    }
    /**
     * @param {boolean} arg0
     */
    set is_left(arg0) {
        wasm.__wbg_set_inputstate_is_left(this.__wbg_ptr, arg0);
    }
    /**
     * @param {boolean} arg0
     */
    set is_mobile(arg0) {
        wasm.__wbg_set_inputstate_is_mobile(this.__wbg_ptr, arg0);
    }
    /**
     * @param {boolean} arg0
     */
    set is_right(arg0) {
        wasm.__wbg_set_inputstate_is_right(this.__wbg_ptr, arg0);
    }
    /**
     * @param {boolean} arg0
     */
    set is_stalled_recovery_key(arg0) {
        wasm.__wbg_set_inputstate_is_stalled_recovery_key(this.__wbg_ptr, arg0);
    }
    /**
     * @param {number} arg0
     */
    set mouse_movement_x(arg0) {
        wasm.__wbg_set_inputstate_mouse_movement_x(this.__wbg_ptr, arg0);
    }
    /**
     * @param {number} arg0
     */
    set mouse_movement_y(arg0) {
        wasm.__wbg_set_inputstate_mouse_movement_y(this.__wbg_ptr, arg0);
    }
}
if (Symbol.dispose) InputState.prototype[Symbol.dispose] = InputState.prototype.free;
function __wbg_get_imports() {
    const import0 = {
        __proto__: null,
        __wbg___wbindgen_throw_344f42d3211c4765: function(arg0, arg1) {
            throw new Error(getStringFromWasm0(arg0, arg1));
        },
        __wbindgen_init_externref_table: function() {
            const table = wasm.__wbindgen_externrefs;
            const offset = table.grow(4);
            table.set(0, undefined);
            table.set(offset + 0, undefined);
            table.set(offset + 1, null);
            table.set(offset + 2, true);
            table.set(offset + 3, false);
        },
    };
    return {
        __proto__: null,
        "./core_engine_bg.js": import0,
    };
}

const GameEngineFinalization = (typeof FinalizationRegistry === 'undefined')
    ? { register: () => {}, unregister: () => {} }
    : new FinalizationRegistry(ptr => wasm.__wbg_gameengine_free(ptr, 1));
const InputStateFinalization = (typeof FinalizationRegistry === 'undefined')
    ? { register: () => {}, unregister: () => {} }
    : new FinalizationRegistry(ptr => wasm.__wbg_inputstate_free(ptr, 1));

function _assertClass(instance, klass) {
    if (!(instance instanceof klass)) {
        throw new Error(`expected instance of ${klass.name}`);
    }
}

function getStringFromWasm0(ptr, len) {
    return decodeText(ptr >>> 0, len);
}

let cachedUint8ArrayMemory0 = null;
function getUint8ArrayMemory0() {
    if (cachedUint8ArrayMemory0 === null || cachedUint8ArrayMemory0.byteLength === 0) {
        cachedUint8ArrayMemory0 = new Uint8Array(wasm.memory.buffer);
    }
    return cachedUint8ArrayMemory0;
}

let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
cachedTextDecoder.decode();
const MAX_SAFARI_DECODE_BYTES = 2146435072;
let numBytesDecoded = 0;
function decodeText(ptr, len) {
    numBytesDecoded += len;
    if (numBytesDecoded >= MAX_SAFARI_DECODE_BYTES) {
        cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
        cachedTextDecoder.decode();
        numBytesDecoded = len;
    }
    return cachedTextDecoder.decode(getUint8ArrayMemory0().subarray(ptr, ptr + len));
}

let wasmModule, wasmInstance, wasm;
function __wbg_finalize_init(instance, module) {
    wasmInstance = instance;
    wasm = instance.exports;
    wasmModule = module;
    cachedUint8ArrayMemory0 = null;
    wasm.__wbindgen_start();
    return wasm;
}

async function __wbg_load(module, imports) {
    if (typeof Response === 'function' && module instanceof Response) {
        if (typeof WebAssembly.instantiateStreaming === 'function') {
            try {
                return await WebAssembly.instantiateStreaming(module, imports);
            } catch (e) {
                const validResponse = module.ok && expectedResponseType(module.type);

                if (validResponse && module.headers.get('Content-Type') !== 'application/wasm') {
                    console.warn("`WebAssembly.instantiateStreaming` failed because your server does not serve Wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n", e);

                } else { throw e; }
            }
        }

        const bytes = await module.arrayBuffer();
        return await WebAssembly.instantiate(bytes, imports);
    } else {
        const instance = await WebAssembly.instantiate(module, imports);

        if (instance instanceof WebAssembly.Instance) {
            return { instance, module };
        } else {
            return instance;
        }
    }

    function expectedResponseType(type) {
        switch (type) {
            case 'basic': case 'cors': case 'default': return true;
        }
        return false;
    }
}

function initSync(module) {
    if (wasm !== undefined) return wasm;


    if (module !== undefined) {
        if (Object.getPrototypeOf(module) === Object.prototype) {
            ({module} = module)
        } else {
            console.warn('using deprecated parameters for `initSync()`; pass a single object instead')
        }
    }

    const imports = __wbg_get_imports();
    if (!(module instanceof WebAssembly.Module)) {
        module = new WebAssembly.Module(module);
    }
    const instance = new WebAssembly.Instance(module, imports);
    return __wbg_finalize_init(instance, module);
}

async function __wbg_init(module_or_path) {
    if (wasm !== undefined) return wasm;


    if (module_or_path !== undefined) {
        if (Object.getPrototypeOf(module_or_path) === Object.prototype) {
            ({module_or_path} = module_or_path)
        } else {
            console.warn('using deprecated parameters for the initialization function; pass a single object instead')
        }
    }

    if (module_or_path === undefined) {
        module_or_path = new URL('core_engine_bg.wasm', import.meta.url);
    }
    const imports = __wbg_get_imports();

    if (typeof module_or_path === 'string' || (typeof Request === 'function' && module_or_path instanceof Request) || (typeof URL === 'function' && module_or_path instanceof URL)) {
        module_or_path = fetch(module_or_path);
    }

    const { instance, module } = await __wbg_load(await module_or_path, imports);

    return __wbg_finalize_init(instance, module);
}

export { initSync, __wbg_init as default };
