/* tslint:disable */
/* eslint-disable */

/**
 * Core flight physics engine for the wireframe shooter.
 * Holds all numerical state — never touches DOM or JS objects.
 */
export class GameEngine {
    free(): void;
    [Symbol.dispose](): void;
    die(): void;
    /**
     * Returns a pointer to the state buffer (18 f32s).
     */
    get_state_ptr(): number;
    /**
     * Returns a pointer to the transform buffer (7 f32s).
     */
    get_transform_ptr(): number;
    /**
     * Returns a pointer to the velocity buffer (3 f32s).
     */
    get_velocity_ptr(): number;
    /**
     * Create a new GameEngine with default flight parameters.
     * `init_x`, `init_z` are the random spawn coordinates generated by JS.
     */
    constructor(init_x: number, init_z: number);
    reset(): void;
    set_hp(value: number): void;
    set_infinite_engines_active(active: boolean): void;
    set_is_stalled(stalled: boolean): void;
    set_pitch(value: number): void;
    set_pos(x: number, y: number, z: number): void;
    set_roll(value: number): void;
    set_shield_active(active: boolean): void;
    set_stall_timer(value: number): void;
    set_yaw(value: number): void;
    tick(dt: number, input: InputState, terrain_height: number, is_intro: boolean): boolean;
    trigger_shake(intensity: number): void;
}

export class InputState {
    free(): void;
    [Symbol.dispose](): void;
    constructor();
    gyro_pitch_amt: number;
    gyro_roll_amt: number;
    is_backward: boolean;
    is_boosting: boolean;
    is_forward: boolean;
    is_left: boolean;
    is_mobile: boolean;
    is_right: boolean;
    is_stalled_recovery_key: boolean;
    mouse_movement_x: number;
    mouse_movement_y: number;
}

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly __wbg_gameengine_free: (a: number, b: number) => void;
    readonly __wbg_get_inputstate_gyro_pitch_amt: (a: number) => number;
    readonly __wbg_get_inputstate_gyro_roll_amt: (a: number) => number;
    readonly __wbg_get_inputstate_is_backward: (a: number) => number;
    readonly __wbg_get_inputstate_is_boosting: (a: number) => number;
    readonly __wbg_get_inputstate_is_forward: (a: number) => number;
    readonly __wbg_get_inputstate_is_left: (a: number) => number;
    readonly __wbg_get_inputstate_is_mobile: (a: number) => number;
    readonly __wbg_get_inputstate_is_right: (a: number) => number;
    readonly __wbg_get_inputstate_is_stalled_recovery_key: (a: number) => number;
    readonly __wbg_get_inputstate_mouse_movement_x: (a: number) => number;
    readonly __wbg_get_inputstate_mouse_movement_y: (a: number) => number;
    readonly __wbg_inputstate_free: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_gyro_pitch_amt: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_gyro_roll_amt: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_is_backward: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_is_boosting: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_is_forward: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_is_left: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_is_mobile: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_is_right: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_is_stalled_recovery_key: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_mouse_movement_x: (a: number, b: number) => void;
    readonly __wbg_set_inputstate_mouse_movement_y: (a: number, b: number) => void;
    readonly gameengine_die: (a: number) => void;
    readonly gameengine_get_state_ptr: (a: number) => number;
    readonly gameengine_get_transform_ptr: (a: number) => number;
    readonly gameengine_get_velocity_ptr: (a: number) => number;
    readonly gameengine_new: (a: number, b: number) => number;
    readonly gameengine_reset: (a: number) => void;
    readonly gameengine_set_hp: (a: number, b: number) => void;
    readonly gameengine_set_infinite_engines_active: (a: number, b: number) => void;
    readonly gameengine_set_is_stalled: (a: number, b: number) => void;
    readonly gameengine_set_pitch: (a: number, b: number) => void;
    readonly gameengine_set_pos: (a: number, b: number, c: number, d: number) => void;
    readonly gameengine_set_roll: (a: number, b: number) => void;
    readonly gameengine_set_shield_active: (a: number, b: number) => void;
    readonly gameengine_set_stall_timer: (a: number, b: number) => void;
    readonly gameengine_set_yaw: (a: number, b: number) => void;
    readonly gameengine_tick: (a: number, b: number, c: number, d: number, e: number) => number;
    readonly gameengine_trigger_shake: (a: number, b: number) => void;
    readonly inputstate_new: () => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
